services:
  car-ml:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: car_ml
    privileged: true
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/i2c-1:/dev/i2c-1
    ports:
      - "5000:5000" # Flask dashboard
    volumes:
      - /data:/data
    networks:
      - obd2_network
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"
        reservations:
          memory: 128M
          cpus: "0.3"

networks:
  obd2_network:
    driver: bridge
